# Generated by Django 2.2.5 on 2019-09-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20190904_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
    ]
