# Generated by Django 2.2.5 on 2019-09-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
